#!/usr/bin/Rscript

#In R
#GENERATING 05TPM

L222.gene.tpm <- L222.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L222{.}"))
L223.gene.tpm<- L223.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L223{.}"))
L224.gene.tpm <- L224.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L224{.}"))
L355.gene.tpm <- L355.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L355{.}"))
L356.gene.tpm <- L356.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L356{.}"))
L357.gene.tpm <- L357.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L357{.}"))
L393.gene.tpm <- L393.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L393{.}"))
L394.gene.tpm <- L394.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L394{.}"))
L395.gene.tpm <- L395.gene.tpm  %>% subset(select = c("Gene", "TpM"))%>% rename_with(.cols = c(2), ~glue::glue("L395{.}"))
library(mergeutils)
tpmlist <- list(L222.gene.tpm,L223.gene.tpm,L224.gene.tpm,L355.gene.tpm,L356.gene.tpm,L357.gene.tpm,L393.gene.tpm,L394.gene.tpm,L395.gene.tpm)
gene.tpm <- multimerge(tpmlist, by = "Gene")
PP.DP.expressed<-subset(gene.tpm, L222TpM>=0.5 & L355TpM>=0.5 & L393TpM>=0.5 & L223TpM>=0.5 & L356TpM>=0.5 & L394TpM>=0.5)
DP.N.expressed<-subset(gene.tpm, L224TpM>=0.5 & L357TpM >=0.5 & L395TpM>=0.5 & L223TpM>=0.5 & L356TpM>=0.5 & L394TpM>=0.5)

L222.psi$name<-gsub(" ", "",paste(L222.psi$Gene, L222.psi$Node, sep="-"))
L223.psi$name<-gsub(" ", "",paste(L223.psi$Gene, L223.psi$Node, sep="-"))
L224.psi$name<-gsub(" ", "",paste(L224.psi$Gene, L224.psi$Node, sep="-"))
L355.psi$name<-gsub(" ", "",paste(L355.psi$Gene, L355.psi$Node, sep="-"))
L356.psi$name<-gsub(" ", "",paste(L356.psi$Gene, L356.psi$Node, sep="-"))
L357.psi$name<-gsub(" ", "",paste(L357.psi$Gene, L357.psi$Node, sep="-"))
L393.psi$name<-gsub(" ", "",paste(L393.psi$Gene, L393.psi$Node, sep="-"))
L394.psi$name<-gsub(" ", "",paste(L394.psi$Gene, L394.psi$Node, sep="-"))
L395.psi$name<-gsub(" ", "",paste(L395.psi$Gene, L395.psi$Node, sep="-"))

L222.c<-subset(L222.psi, CI_Width<=0.3)
L223.c<-subset(L223.psi, CI_Width<=0.3)
L224.c<-subset(L224.psi, CI_Width<=0.3)
L355.c<-subset(L355.psi, CI_Width<=0.3)
L356.c<-subset(L356.psi, CI_Width<=0.3)
L357.c<-subset(L357.psi, CI_Width<=0.3)
L393.c<-subset(L393.psi, CI_Width<=0.3)
L394.c<-subset(L394.psi, CI_Width<=0.3)
L395.c<-subset(L395.psi, CI_Width<=0.3)

PP.DP.DPSI.diff.diff$name<-gsub(" ", "",paste(PP.DP.DPSI.diff.diff$Gene, PP.DP.DPSI.diff.diff$Node, sep="-"))
DP.N.DPSI.diff.diff$name<-gsub(" ", "",paste(DP.N.DPSI.diff.diff$Gene, DP.N.DPSI.diff.diff$Node, sep="-"))
expressedPPDP<-subset(PP.DP.DPSI.diff.diff, PP.DP.DPSI.diff.diff$Gene %in% PP.DP.expressed$Gene)
expressedDPN<-subset(DP.N.DPSI.diff.diff, DP.N.DPSI.diff.diff$Gene %in% DP.N.expressed$Gene)
confidencePPDP<-subset(expressedPPDP, expressedPPDP$name %in% L222.c$name & expressedPPDP$name %in% L355.c$name & expressedPPDP$name %in% L393.c$name & expressedPPDP$name %in% L223.c$name & expressedPPDP$name %in% L356.c$name & expressedPPDP$name %in% L394.c$name)
confidenceDPN<-subset(expressedDPN, expressedDPN$name %in% L222.c$name & expressedDPN$name %in% L355.c$name & expressedDPN$name %in% L393.c$name & expressedDPN$name %in% L223.c$name & expressedDPN$name %in% L356.c$name & expressedDPN$name %in% L394.c$name)
whip.exons.PP.DP<-subset(confidencePPDP, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")
whip.exons.PP.DP.nc<-subset(expressedPPDP, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")
whip.exons.DP.N<-subset(confidenceDPN, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")
whip.exons.DP.N.nc<-subset(expressedDPN, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")

whippet.splicedPPDP<-subset(confidencePPDP, Probability>=0.9 & DeltaPsi >=0.1 | Probability>=0.9 & DeltaPsi <=-0.1)
whip.act.spliced.PP.DP<-subset(whippet.splicedPPDP, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")
whippet.splicedDPN<-subset(confidenceDPN, Probability>=0.9 & DeltaPsi >=0.1 | Probability>=0.9 & DeltaPsi <=-0.1)
whip.act.spliced.DPN<-subset(whippet.splicedDPN, Type=="CE" | Type=="AA" | Type=="AD" | Type=="RI")
whip.act.spliced.PP.DPcoord <- whip.act.spliced.PP.DP %>% mutate(V4 = "1")%>% subset(select = c("Coord", "name", "V4", "Strand")) 
whip.act.spliced.DP.Ncoord <- whip.act.spliced.DPN%>% mutate(V4 = "1") %>% subset(select = c("Coord", "name","V4", "Strand"))
